### ISSUE TITLE
As a Südtirol Guide Product Manager I would like that the Gamification Module is implemented in the app without bugs.

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/beacon-gamification-module#28]
As Johannes from Konverto reported, the lately discovered problem in the version 5.8.7 (app crashed while running the gamification module every time the device was in proximity of a beacon) may depend on the api of the beacon sdk.

He wrote:
"Wir vermuten stark dass die Api hier mittlerweile ein anderes Schema zurückliefert als sich die App erwartet. Das zumindest ist unsere Schlussfolgerung wenn wir die Commits im Repo ansehen. Leider können wir genau diesen Endpoint nicht aufrufen, da es jener des Battery Levels ist, welcher ja mit den Kredenzialien geschützt ist welche wir nicht haben."

**Comment by RudiThoeni** [comment]
Peter & Patrick will see if a short workaround is possible with this issue. For the future the sdk has to work properly and all workarounds are to integrate there.

**Comment by ohnewein** [comment]
If the app is not able to handle schema variations, but crashes it is a horrible app. Who developed this app?

**Comment by niettadesantis** [comment]
> If the app is not able to handle schema variations, but crashes it is a horrible app. Who developed this app?

Someone that will no longer do it in future.

**Comment by ohnewein** [comment]
> 
> Someone that will no longer do it in future.

I see. 

I think we need to improve automated testing and quality assurance, as well introduce a kind of verification program for software developers.

**Comment by bertolla** [comment]
Yeah, I mean, if the schema did change, it means that the returned API model changed, which normally should have the consequence to increase the version of the API and to release a new version of the sdk with the new/changed api calls implemented.
Our beacon SDK is throwing the exception not the suedtirol mobile guide(I checked crashlitics).
```
Fatal Exception: java.lang.AbstractMethodError: abstract method "java.lang.Object c.c.e.w.b(com.google.gson.stream.JsonReader)"
       at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:15)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:2)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:47)
       at com.google.gson.Gson.fromJson(Gson.java:20)
       at com.google.gson.Gson.fromJson(Gson.java:4)
       at com.google.gson.Gson.fromJson(Gson.java:9)
       at it.bz.beacon.beaconsuedtirolsdk.swagger.client.JSON.deserialize(JSON.java:27)
       at it.bz.beacon.beaconsuedtirolsdk.swagger.client.ApiClient.deserialize(ApiClient.java:97)
       at it.bz.beacon.beaconsuedtirolsdk.swagger.client.ApiClient.handleResponse(ApiClient.java:18)
       at it.bz.beacon.beaconsuedtirolsdk.swagger.client.ApiClient.execute(ApiClient.java:4)
       at it.bz.beacon.beaconsuedtirolsdk.swagger.client.api.TrustedBeaconControllerApi.updateUsingPATCH1WithHttpInfo(TrustedBeaconControllerApi.java:16)
       at it.bz.beacon.beaconsuedtirolsdk.swagger.client.api.TrustedBeaconControllerApi.updateUsingPATCH1(TrustedBeaconControllerApi.java)
       at it.bz.beacon.beaconsuedtirolsdk.data.repository.BatteryLevelInfoRepository$1.run(BatteryLevelInfoRepository.java:130)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by Piiit** [comment]
The thing is that we did not introduce a new version, because we did not change the API, but only added things... to keep things simpler we decided to keep the version. We did the same also for other APIs, just changing versions if schemas have been changed (that is, attributes deleted or changed)... The problem here is thou, that the SDK is in between, that wasn't probably updated correctly. We need SDK testing as well...

Another possible unconventional solution could be to drop the SDK and use API calls directly

**Comment by ohnewein** [comment]
> The thing is that we did not introduce a new version, because we did not change the API, but only added things... to keep things simpler we decided to keep the version. We did the same also for other APIs, just changing versions if schemas have been changed (that is, attributes deleted or changed)... The problem here is thou, that the SDK is in between, that wasn't probably updated correctly. We need SDK testing as well...
> 
> Another possible unconventional solution could be to drop the SDK and use API calls directly

That means not the app is horrible, but the SDK.

I would be in favor to drop the SDK, if there is no real technical reason for it to exist. Less is more!

**Comment by Piiit** [comment]
We need to check where the problem is... can't say anything just like this...

**Comment by Piiit** [comment]
Update:
- Fixed the Android SDK which now has the correct ORM mappings between the new API and the classes on Java 
- It builds and CIs are ok, but the suedtirol guide still crashes
- Integrated the new SDK into the react-native-sdk (seems to work, but only testable with a s.guide integration)
- Next step is needed for debbuging: I need to build the guide on my local machine and integrate the new version, debug and see where the problem is

- The IOS sdk will be last, after testing all parts on android

**Comment by bertolla** [comment]
By backporting to the 0.4.2 SDK we were able to avoid crashes on the live app. We tried to release a Version 0.5.0-SNAPSHOT in the Alpha-Channel but the issue still persists.
@Piiit 
With the latest snapshot we still have the same problem. You reported another kind of issue. Can you solve it, are you working on it?

**Comment by bertolla** [comment]
The crash itself was not caused by the wrong schema, like suspected, but by the minifying of the schema models.
We just had to disable the minifying in the proguard rules of the suedtirolapp-android https://github.com/noi-techpark/suedtirolapp-android/commit/5fbef550ec0d38cb6eef33476d838711d095a388

**Comment by bertolla** [comment]
To summarize:
- suedtirol app production release is 5.8.11 containing the backport to 0.4.2 beacon sdk
- suedtirol app test release is 5.9.2 containing the backport to 0.6.0 beacon sdk with working battery status update
- as soon as we got the ok from IDM to release  5.9.2 to production we will also release the gamification to test as 5.10.0 containing the beacon-sdk 0.6.0

**Comment by niettadesantis** [comment]
Will test the gamification next tuesday (Aug. 24th) in Merano.

**Comment by niettadesantis** [comment]
The test was succesfull, gamification worked well.
